class ChangeProcurements < ActiveRecord::Migration
  def change
    execute "DROP TABLE IF EXISTS procurements"
    execute "DROP TABLE IF EXISTS temp_procurements"
    create_table :procurements do |t|
      t.string :zmluva_hodnota
      t.text :zakazka_nazov
      t.string :vestnik_cislo
      t.string :source_url
      t.string :date_year
      t.string :date_month
      t.string :date_month_name
      t.string :date_month_sname
      t.string :date_id
      t.string :date_day
      t.string :cpv_division
      t.string :cpv_division_label
      t.string :cpv_division_compet
      t.string :cpv_group
      t.string :cpv_group_label
      t.string :cpv_group_compet
      t.string :cpv_class
      t.string :cpv_class_label
      t.string :cpv_class_compet
      t.string :cpv_category
      t.string :cpv_category_label
      t.string :cpv_category_compet
      t.string :cpv_id
      t.string :cpv_detail
      t.string :cpv_detail_label
      t.string :cpv_code
      t.string :cpv_detail_compet
      t.string :procurer_account_sector_code
      t.string :procurer_account_sector
      t.string :procurer_id
      t.string :procurer_ico
      t.string :procurer_name
      t.string :procurer_region
      t.string :procurer_address
      t.string :procurer_legal_form
      t.string :procurer_offer_count_avg
      t.string :procurer_competitiveness
      t.string :supplier_id
      t.string :supplier_ico
      t.string :supplier_name
      t.string :supplier_address
      t.string :supplier_country
      t.string :supplier_date_start
      t.string :supplier_date_end
      t.string :supplier_legal_form
      t.string :supplier_ownership
      t.string :supplier_offer_count_avg
      t.string :supplier_competitiveness
      t.string :druh_postupu_id
      t.string :druh_postupu_code
      t.string :druh_postupu_description
      t.string :druh_postupu_sdesc
      t.string :kriteria_vyhodnotenia_code
      t.text :kriteria_vyhodnotenia_description
      t.text :kriteria_vyhodnotenia_sdesc
      t.string :kriteria_vyhodnotenia_id
      t.string :geography_kraj_code
      t.string :geography_kraj
      t.string :geography_okres_code
      t.string :geography_okres
      #doplnene z ft_vvo_contracts
      t.string :document_id
      t.string :pocet_ponuk
      t.string :druh_zakazky_id
      t.string :druh_zakazky_code
      t.string :druh_zakazky
      t.string :elektronicka_aukcia_flag
      t.string :zakazka_eurofondy_flag
      ##########
      t.integer :document_detail
      t.string :document_detail_type
    end

    create_table :temp_procurements do |t|
      t.string :zmluva_hodnota
      t.text :zakazka_nazov
      t.string :vestnik_cislo	
      t.string :source_url	
      t.string :date_year	
      t.string :date_month	
      t.string :date_month_name	
      t.string :date_month_sname	
      t.string :date_id
      t.string :date_day	
      t.string :cpv_division	
      t.string :cpv_division_label	
      t.string :cpv_division_compet	
      t.string :cpv_group	
      t.string :cpv_group_label	
      t.string :cpv_group_compet	
      t.string :cpv_class	
      t.string :cpv_class_label	
      t.string :cpv_class_compet	
      t.string :cpv_category	
      t.string :cpv_category_label	
      t.string :cpv_category_compet	
      t.string :cpv_id	
      t.string :cpv_detail	
      t.string :cpv_detail_label	
      t.string :cpv_code	
      t.string :cpv_detail_compet	
      t.string :procurer_account_sector_code	
      t.string :procurer_account_sector	
      t.string :procurer_id	
      t.string :procurer_ico	
      t.string :procurer_name	
      t.string :procurer_region	
      t.string :procurer_address	
      t.string :procurer_legal_form	
      t.string :procurer_offer_count_avg	
      t.string :procurer_competitiveness	
      t.string :supplier_id
      t.string :supplier_ico
      t.string :supplier_name	
      t.string :supplier_address	
      t.string :supplier_country	
      t.string :supplier_date_start	
      t.string :supplier_date_end	
      t.string :supplier_legal_form	
      t.string :supplier_ownership	
      t.string :supplier_offer_count_avg	
      t.string :supplier_competitiveness	
      t.string :druh_postupu_id	
      t.string :druh_postupu_code	
      t.string :druh_postupu_description	
      t.string :druh_postupu_sdesc	
      t.string :kriteria_vyhodnotenia_code	
      t.text :kriteria_vyhodnotenia_description
      t.text :kriteria_vyhodnotenia_sdesc
      t.string :kriteria_vyhodnotenia_id	
      t.string :geography_kraj_code	
      t.string :geography_kraj	
      t.string :geography_okres_code
      t.string :geography_okres
    end

    create_table :ft_vvo_contracts do |t|
      t.string :document_id
      t.string :document_code
      t.string :contract_key
      t.string :document_type_code
      t.string :vz_flag
      t.string :vestnik_cislo
      t.string :cislo_oznamenia
      t.string :source_url
      t.string :bulletin_date_id
      t.string :bulletin_date
      t.text :zakazka_nazov
      t.string :druh_postupu_id
      t.string :druh_postupu_code
      t.string :druh_postupu
      t.string :druh_zakazky_id
      t.string :druh_zakazky_code
      t.string :druh_zakazky
      t.string :kriteria_vyhodnotenia_id
      t.string :kriteria_vyhodnotenia_code
      t.string :kriteria_vyhodnotenia
      t.string :elektronicka_aukcia_flag
      t.string :zakazka_eurofondy_flag
      t.string :cpv_id
      t.string :cpv_code
      t.string :obstaravatel_id
      t.string :obstaravatel_ico
      t.string :obstaravatel_region
      t.string :obstaravatel_nazov
      t.string :obstaravatel_sektor_id
      t.string :obstaravatel_sektor
      t.string :obstaravatel_contact_email
      t.string :obstaravatel_contact_phone
      t.string :obstaravatel_contact_url
      t.string :obstaravatel_contact_person
      t.string :dodavatel_id
      t.string :dodavatel_ico
      t.string :dodavatel_region
      t.string :dodavatel_nazov
      t.string :dodavatel_stat
      t.string :dodavatel_sektor_id
      t.string :dodavatel_sektor
      t.string :geography_id
      t.string :predpoklad_subdodavok
      t.string :pocet_ponuk
      t.string :pocet_zmluv
      t.string :zakazka_hodnota
      t.string :zakazka_currency
      t.string :zmluva_hodnota
      t.string :zmluva_currency
    end
  end
end
